# Generated by Django 4.1.7 on 2023-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='qweasd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
